# .gitpod.yml
image: python:3.10

ports:
  - port: 8000
    onOpen: ignore
  - port: 3000
    onOpen: open-browser

tasks:
  - init: |
      cd backend
      python3 -m venv venv
      source venv/bin/activate
      pip install -r requirements.txt
      touch app/__init__.py
      touch app/services/__init__.py
    command: sleep 1  # dummy command to avoid blocking
  - init: |
      cd frontend/aura-ai-ui
      npm install
      echo "NEXT_PUBLIC_API_URL=http://localhost:8000/" > .env.local
    command: sleep 1

# Start both frontend and backend concurrently using gp/supervisor
github:
  prebuilds:
    master: true

vscode:
  extensions:
    - ms-python.python
    - esbenp.prettier-vscode

# Use Gitpod's supervisor to run both apps
supervisor:
  processes:
    - name: backend
      command: >
        bash -c "cd backend/app && source ../venv/bin/activate && uvicorn main:app --reload --host 0.0.0.0 --port 8000"
    - name: frontend
      command: >
        bash -c "cd frontend/aura-ai-ui && npm run dev --port 3000"
