image: python:3.10

ports:
  - port: 8000
    onOpen: ignore           # FastAPI backend
  - port: 3000
    onOpen: open-browser     # Next.js frontend

tasks:
  - name: Setup and Run Backend + Frontend
    init: |
      # Setup backend
      cd backend
      python3 -m venv venv
      source venv/bin/activate
      pip install -r requirements.txt
      touch app/__init__.py
      touch app/services/__init__.py
      cd ..

      # Setup frontend
      cd frontend/aura-ai-ui
      npm install
      echo "NEXT_PUBLIC_API_URL=http://localhost:8000/" > .env.local
      cd ../../

    command: |
      # Run backend in background
      cd backend/app
      source ../venv/bin/activate
      uvicorn main:app --reload --host 0.0.0.0 --port 8000 &

      # Run frontend in foreground
      cd ../../frontend/aura-ai-ui
      npm run dev --port 3000
