# .gitpod.yml
# Gitpod configuration for Aura AI Hackathon Project
# This YAML is validated for correct Gitpod syntax.

# Define the base image for the workspace
# Using a Node.js image that has Python pre-installed for convenience
image: gitpod/workspace-full-nodejs

# Configure ports and how they are exposed
ports:
  - port: 8000 # Backend FastAPI
    onOpen: ignore # Don't open automatically, we'll open frontend
  - port: 3000 # Frontend Next.js Dev Server
    onOpen: open-browser # Automatically open the browser to the frontend

# Define tasks to run when the workspace starts
tasks:
  # Task to set up and run the Backend
  - name: Setup Backend & Run
    init: |
      # Navigate to backend directory
      cd backend
      # Create and activate Python virtual environment
      python3 -m venv venv
      source venv/bin/activate
      # Install backend dependencies
      pip install -r requirements.txt
      # Ensure __init__.py files exist (if not already committed)
      touch app/__init__.py
      touch app/services/__init__.py
    command: |
      # Once init is done, start the backend server
      cd backend/app # Navigate into the app directory for running
      source ../venv/bin/activate # Activate venv relative to backend/app
      uvicorn main:app --reload --host 0.0.0.0 --port 8000 # Listen on 0.0.0.0 for Gitpod exposure
    # openMode: split-right # Removed, as this is often where the validation error occurs for "allowed values"

  # Task to set up and run the Frontend
  - name: Setup Frontend & Run
    init: |
      # Navigate to frontend directory
      cd frontend/aura-ai-ui
      # Install frontend dependencies
      npm install
      # Create .env.local for frontend to connect to local backend
      echo "NEXT_PUBLIC_API_URL=http://localhost:8000/" > .env.local
    command: |
      # Once init is done, start the frontend server
      cd frontend/aura-ai-ui # Ensure current directory is frontend app root
      npm run dev --port 3000 # Specify port, Gitpod will expose
    # openMode: split-bottom # Removed, as this is often where the validation error occurs for "allowed values"